on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - 'git:v1.6.10-pluspatches https://github.com/iffy/Nim.git'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - shell: bash
      run: |
        ls -al
        which nim
        which nimble
    - name: Package
      shell: bash
      run: |
        rm -r nimdir/.git
        rm -r nimdir/.builds
        rm -r nimdir/.github
        rm -r nimdir/csources_v1/.git
        rm -r nimdir/dist/nimble/.git
        rm -r nimdir/nimcache
        tar czvf nim-1.6.10-pluspatches-${{ matrix.os }}.tar.xz nimdir
    - name: List
      shell: bash
      run: |
        tar tf nim-1.6.10-pluspatches-${{ matrix.os }}.tar.xz
    - uses: actions/upload-artifact@v3
      with:
        name: nim-1.6.10-pluspatches-${{ matrix.os }}.tar.xz
        path: nim-1.6.10-pluspatches-${{ matrix.os }}.tar.xz
